### PR TITLE
Store error as Error instance

### PR DESCRIPTION
**Pull request by kelonye**
Need to be able to lookup rejected error.

### CODE REVIEW

**Comment by KELiON** [comment]
@kelonye agree! One question – why did you remove `lib` from gitignore? Build is not needed in repo, needed only for publishing npm package, so it can be removed from the repo

**Comment by kelonye** [comment]
Oh I had meant to mention that the latest commit should be removed in the merge. Needed it to specify the version in my package.json:

```"redux-async-initial-state": "kelonye/redux-async-initial-state"```

**Comment by kelonye** [comment]
All good now. Please publish if you ever merge :)

**Comment by KELiON** [comment]
@kelonye done!

**Comment by kelonye** [comment]
👏

**Pull request merged**
