### PR TITLE
Pass store.getState to get latest state on promise resolution

### PR DESCRIPTION
**Pull request by tuntisz**
https://github.com/KELiON/redux-async-initial-state/issues/11

### CODE REVIEW

**Comment by KELiON** [comment]
@tuntisz Why did you closed this PR?

**Comment by tuntisz** [comment]
I committed breaking changes in my fork. Would you like me to reopen with a cleaner fix?

**Comment by KELiON** [comment]
@tuntisz I think it totally makes sense and deserve a major release to prevent broken builds after package update

**Comment by jdolle** [comment]
Is this still being addressed? If you'd like, I'd be happy to work on this.

**Comment by conor909** [comment]
can we get this merged in?  or this still maintained at all?

**Pull request closed without merging**
